# Generated by Django 5.0.6 on 2024-06-09 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('localization', models.CharField(max_length=100)),
                ('money_profit', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('setting_type', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('outfit_type', models.CharField(max_length=100)),
                ('leaving_location', models.CharField(max_length=100)),
                ('leaving_time', models.CharField(max_length=100)),
                ('organizator', models.CharField(max_length=100)),
                ('organizator_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=100)),
                ('guest_inquiry', models.CharField(max_length=255)),
                ('guest_unique_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composer', models.ManyToManyField(to='band_main.composer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_main.song'),
        ),
        migrations.CreateModel(
            name='SummaryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_profit_total', models.FloatField()),
                ('monthly_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_main.event')),
            ],
        ),
    ]
