# Generated by Django 5.0.6 on 2024-06-10 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('color', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuestPanel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizator_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='outfit_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='setting_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='song',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_main.organizator'),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.AddField(
            model_name='event',
            name='song',
            field=models.ManyToManyField(to='band_main.song'),
        ),
    ]
